// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.DataModel;

#nullable disable

namespace TestTask.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20230107202410_lastmigration")]
    partial class lastmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Accounts", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IncidentsIncidentName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("IncidentsIncidentName");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TestTask.Contacts", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountsName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.HasIndex("AccountsName");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TestTask.Incidents", b =>
                {
                    b.Property<string>("IncidentName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentName");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("TestTask.Accounts", b =>
                {
                    b.HasOne("TestTask.Incidents", "Incidents")
                        .WithMany()
                        .HasForeignKey("IncidentsIncidentName");

                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("TestTask.Contacts", b =>
                {
                    b.HasOne("TestTask.Accounts", "Accounts")
                        .WithMany()
                        .HasForeignKey("AccountsName");

                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
